### ISSUE TITLE
TS Error: Unable to resolve signature of property decorator when called as an expression.

### ISSUE THREAD

**Issue by speigg** [pzuraq/tracked-built-ins#19]
The typings for the `tracked` decorator in the npm package are missing an optional specifier:

```typescript
export default function tracked(obj: object, key: string | symbol, desc: PropertyDescriptor): void;
```

should be: 

```typescript
export default function tracked(obj: object, key: string | symbol, desc?: PropertyDescriptor): void;
```

**Comment by pzuraq** [comment]
Thanks for bringing this up, can you open a PR to fix by chance? If not I should be able to get to it soon.

**Comment by speigg** [comment]
It's not actually clear to me why the type definitions you are generating are missing the optional specifier. The `.ts` source has the correct typings.

**Comment by pzuraq** [comment]
This line is probably the incorrect one: https://github.com/pzuraq/tracked-built-ins/blob/master/addon/-private/decorator.ts#L40

**Comment by speigg** [comment]
Oh, I guess the parameters in the actually implementation are not actually included. I'll open a PR
