### ISSUE TITLE
Issue with TrackedObject in a getter

### ISSUE THREAD

**Issue by jstys** [pzuraq/tracked-built-ins#21]
I'm new to this project so please let me know if this is a usage error on my end, saw it during the presentation at emberconf / in the emberjs subreddit and wanted to give it a shot.  

I've created a `TrackedObject` on one of my components as follows:
```javascript
entriesToDelete = tracked({});
```

I have a getter function that returns the number of entries in the `TrackedObject`:
```javascript
get numEntriesToDelete() {
   return Object.keys(this.entriesToDelete).length;
}
```

I'm seeing the getter work properly when used within the same class, for instance i have some conditional logic where I show a popup dialog:
```javascript
@action
    showDeleteDialog() {
        if (this.numEntriesToDelete > 0) {
            this.isDeleteDialogVisible = true;
        }
        else {
            this.toast.warning("No entries selected for deletion", "Warning", {});
        }
    }
```

But the problem comes when I try to pass the result of the getter as an argument to another component:
```handlebars
@numEntries={{this.numEntriesToDelete}}
```

The result is `@numEntries` in the other component is always returning 0 whereas the `console.log` within the original component always has the correct value.  If I revert back to using a regular object with re-assignments whenever a value changes in the object my logic works as expected.

**Comment by pzuraq** [comment]
Hmm, I don't believe `Object.keys` will actually autotrack correctly. The action works because it's not triggered by autotracking, but by user interaction.

I'll see if I can get a fix up for this, should be pretty straightforward.

**Comment by jstys** [comment]
Okay great, thanks for the feedback, does this same reason apply to deleting keys from a `TrackedObject`?
