### ISSUE TITLE
TrackedArray missing types

### ISSUE THREAD

**Issue by NullVoxPopuli** [pzuraq/tracked-built-ins#41]
A tracked array's type from a consumer app _only_ has these properties: https://github.com/pzuraq/tracked-built-ins/blob/master/addon/-private/array.ts#L110-L121

but we can use all of these: https://github.com/pzuraq/tracked-built-ins/blob/master/addon/-private/array.ts#L9-L32
but typescript is not aware of them, cause Proxies and TS are.. not great :upside_down_face: 

Since `Object.setPrototypeOf(TrackedArray.prototype, Array.prototype);` is a thing, I wonder if the TrackedArray class should extend from Array? idk

**Comment by chriskrycho** [comment]
This is resolve by v1.1.1 (via #56)!
