### ISSUE TITLE
TrackedSet not propagating change notifications correctly for `#each` template helper

### ISSUE THREAD

**Issue by mwpastore** [pzuraq/tracked-built-ins#9]
I have a TrackedSet and some actions to add and remove elements. The `#each` template helper shows the initial contents of the TrackedSet, but does not seem to reflect any changes. Oddly enough, `#each-in` works great (the "key" is the index). 

It's not clear to me whether or not this is something that is supposed to work, but it'd be cooler if it did. Ember 3.15.0, tracked-built-ins 0.2.0.

**Comment by pzuraq** [comment]
This has been fixed in v1.0.0 😄

**Comment by mwpastore** [comment]
Fantastic! Thank you!
